# Generated by Django 4.0.3 on 2022-04-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_field', models.CharField(max_length=32, verbose_name='IP адрес')),
                ('datetime_field', models.DateTimeField(verbose_name='дата')),
                ('status', models.PositiveSmallIntegerField(verbose_name='статус код')),
            ],
            options={
                'verbose_name_plural': 'Logs',
                'ordering': ['-datetime_field'],
            },
        ),
    ]
